apiVersion: v1
kind: Service
metadata:
  name: earthquake-service
  namespace: earthquake-app
spec:
  selector:
    app: earthquake-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
